spring.application.name=CarService
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:carservice
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true

api.key=demo-key-2026